Concensus/Concensus/WSD.Consensus.WebApp/Controllers/GameCreationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading;
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using WSD.Consensus.Presentation.Extensions;
using WSD.Consensus.Configuration.Helpers;
using WSD.Consensus.Core.Contracts;
using WSD.Consensus.Domain.Models;
using WSD.Consensus.Configuration;
using System.Xml;

namespace WSD.Consensus.WebApp.Controllers
{
    public class GameCreationController : Controller
    {
        private readonly IUserBusinessLogic _userBusinessLogic;
        private readonly IUserGameBusinessLogic _userGameBusinessLogic;
        private readonly IUserRatingBusinessLogic _userRatingBusinessLogic;
        private readonly IMedicalCaseBusinessLogic _medicalCaseBusinessLogic;
        private readonly IMedicalTestBusinessLogic _medicalTestBusinessLogic;
        private readonly IMedicalCaseRatingBusinessLogic _medicalCaseRatingBusinessLogic;
        private readonly IMediaBusinessLogic _mediaBusinessLogic;
        private readonly IDiseaseBusinessLogic _diseaseBusinessLogic;
        private readonly ISymptomBusinessLogic _symptomBusinessLogic;
        private readonly IBodyPartBusinessLogic _bodyPartBusinessLogic;
        private readonly IConsensusCache _consensusCache;

        public GameCreationController(
            IConsensusCache consensusCache,
            IUserBusinessLogic userBusinessLogic,
         IUserGameBusinessLogic userGameBusinessLogic,
         IUserRatingBusinessLogic userRatingBusinessLogic,
         IMedicalCaseBusinessLogic medicalCaseBusinessLogic,
         IMedicalCaseRatingBusinessLogic medicalCaseRatingBusinessLogic,
         IMedicalTestBusinessLogic medicalTestBusinessLogic,
         IMediaBusinessLogic mediaBusinessLogic,
         IDiseaseBusinessLogic diseaseBusinessLogic,
         ISymptomBusinessLogic symptomBusinessLogic,
         IBodyPartBusinessLogic bodyPartBusinessLogic)
        {
            _consensusCache = consensusCache;
            _userBusinessLogic = userBusinessLogic;
            _mediaBusinessLogic = mediaBusinessLogic;
            _diseaseBusinessLogic = diseaseBusinessLogic;
            _medicalTestBusinessLogic = medicalTestBusinessLogic;
            _symptomBusinessLogic = symptomBusinessLogic;
            _bodyPartBusinessLogic = bodyPartBusinessLogic;
            _userGameBusinessLogic = userGameBusinessLogic;
            _userRatingBusinessLogic = userRatingBusinessLogic;
            _medicalCaseBusinessLogic = medicalCaseBusinessLogic;
            _medicalCaseRatingBusinessLogic = medicalCaseRatingBusinessLogic;
        }
        // GET: Ga
        // GET: GameCreation

        public ActionResult Index()
        {
            if (GetCurrentUser() == null)
            {
                return Redirect("/Home/Index");
            }
            return View(_medicalCaseBusinessLogic.Search(new MedicalCaseSearch
            {
                CreatorId = GetCurrentUser().Id
            },int.MaxValue,1)?? new List<MedicalCaseModel>());
        }

        private UserModel GetCurrentUser()
        {
            return HttpContext.Session.GetModel<UserModel>("User");
        }

        public ViewResult TypeCreation()
        {
            return View();
        }

        public JsonResult MedicalTestAutoComplete(string term)
        {
            try
            {
                return
                    Json(_medicalTestBusinessLogic.SearchMedicalTests(null, term, GetCurrentUser().CultureName)
                    .Select( x=> x.Id+ ":Test Name:"+x.Name +":"+ 
                    (x.DiseasesToProvePresenceOf != null && x.DiseasesToProvePresenceOf.Any() ? 
                    " Disease Present:" + x.DiseasesToProvePresenceOf.First().ScientificName :"")).Distinct());
            }
            catch 
            {
                throw;
                
            }
        }

        public JsonResult DiseaseAutoComplete(string term)
        {
            try
            {
                var dis = _consensusCache.SearchDiseasesByQuery(new MetaDataSearchQuery
                {
                    DoDbLookUpIfFails = true,
                    ScientificName = term,
                    CultureName = GetCurrentUser().CultureName,
                    NumRowsReturned = 50,
                    PageIndex = 0
                });
                return
                    Json(dis.Select(x => x.Id + "-" + x.ScientificName + "-" + (x.CommonName??"")).Distinct());
            }
            catch (Exception ex)
            {
                return Json(new {Success= false, FriendlyMessage = ex.Message});
            }
        }
        public JsonResult BodyPartsAutoComplete(string term)
        {
            try
            {
                var bps = _consensusCache.SearchSymptomsByQuery(new MetaDataSearchQuery
                {
                    DoDbLookUpIfFails = true,
                    ScientificName = term,
                    CultureName = GetCurrentUser().CultureName,
                    NumRowsReturned = 50,
                    PageIndex = 0
                });
                return
                    Json(bps.Select(x => x.Id + "-" + x.ScientificName + "-" + (x.CommonName??"")).Distinct());
            }
            catch (Exception ex)
            {
                return Json(new { Success = false, FriendlyMessage = ex.Message });
            }
        }

        public JsonResult SymptomAutoComplete(string term)
        {
            try
            {
                var syms = _consensusCache.SearchSymptomsByQuery(new MetaDataSearchQuery
                {
                    DoDbLookUpIfFails = true,
                    ScientificName = term,
                    CultureName = GetCurrentUser().CultureName,
                    NumRowsReturned = 50,
                    PageIndex = 0
                });
                return
                    Json(syms.Select( x=> x.Id +"-"+ x.ScientificName + "-" + (x.CommonName??"")).Distinct());
            }
            catch (Exception ex)
            {
                return Json(new { Success = false, FriendlyMessage = ex.Message });
            }
        }
        public JsonResult CreateSymptom(SymptomModel model)
        {
            model.CultureName = GetCurrentUser().CultureName;
            try
            {
                _symptomBusinessLogic.CreateSymptom(model.ScientificName, model.CommonName, model.CultureName);
                return Json(new
                {
                    Success = true
                });

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Error = ex.Message,
                    Success = false,
                    FriendlyMessage = "Failed To Create  Symptom"
                });
            }
        }
        public JsonResult CreateDisease(DiseaseModel model)
        {
            model.CultureName = GetCurrentUser().CultureName;
            try
            {
                _diseaseBusinessLogic.CreateDisease(model.ScientificName, model.CommonName, model.CultureName);
                return Json(new
                {
                    Success = true
                });

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Error = ex.Message,
                    Success = false,
                    FriendlyMessage = "Failed To Create Disease"
                });
            }
        }
        public JsonResult CreateBodyPart(BodyPartModel model)
        {
            model.CultureName = GetCurrentUser().CultureName;
            try
            {
                _bodyPartBusinessLogic.CreateBodyPart(model.ScientificName,model.CommonName,model.CultureName);
                return Json(new
                {
                    Success = true
                });

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Error = ex.Message,
                    Success = false,
                    FriendlyMessage = "Failed To Create Body Part"
                });
            }
        }

        public ViewResult CreateMedicalTestPopup()
        {

            return View();
        }

        public JsonResult SearchMedicalTests(string name)
        {
            try
            {
                return
                    Json(new 
                    {
                        MedicalTests =_medicalTestBusinessLogic.SearchMedicalTests(null, name, GetCurrentUser().CultureName).Select(x => x.Name),
                        Success = true
                    });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Error = ex.Message,
                    Success = false,
                    FriendlyMessage = "Failed To Find Medical Tests"
                });   
            }
        }

        public JsonResult CreateMedicalTest(MedicalTestModel model, TestResultModel result, DiseaseModel disease)
        {
            model.Name = model.Name.Replace(":", "");
            try
            {
                _medicalTestBusinessLogic.CreateMedicalTest(null,model, result, disease);
                return Json(new
                {
                    Success = true
                });

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Error = ex.Message,
                    Success = false,
                    FriendlyMessage = "Could Not Create Medical Test"
                });
            }
        }
        [HttpGet]
        public ActionResult CreateMedicalCase()
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return
                View(new MedicalCaseModel
                {

Concensus/Concensus/WSD.Consensus.WebApp/Views/Shared/_Layout.cshtml
@using WSD.Consensus.Domain.Models
@using WSD.Consensus.Presentation.Extensions

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MD Consensus</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/jquery.mobile-1.4.5.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/modernizr-2.8.3.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-min-1.10.2.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.fancybox.pack.js"></script>
    <link href="~/css/tablesorterstyle.css" type="text/css" rel="stylesheet" />
    <link href="~/css/jquery.tablesorter.pager.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/jquery.tablesorter.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.tablesorter.pager.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.filtertable.min.js"></script>
    <script type="text/javascript" src="~/Scripts/ConsensusFramework.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MD Consensus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Download The Game", "Downloads", "Home")</li>
                    @if (Context.Session.GetModel<UserModel>("User") != null)
                    {
                        <li><a href="~/MDConsensusHtml5/index.html">Play The Game Online</a></li>
                        <li>@Html.ActionLink("Create Game Level", "Index", "GameCreation")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><a href="/Home/Tos">Terms Of Service</a></p>
            <p>&copy; @DateTime.Now.Year - Powered By Wooden Software Development LLC</p>
        </footer>
    </div>
     
   
     @RenderSection("scripts", required: false)
</body>
</html>